[MB2HAL_INIT]
INIT_DEBUG=6
VERSION=1.1
#HAL_MODULE_NAME=mb2hal
SLOWDOWN=0.0
TOTAL_TRANSACTIONS=2

[TRANSACTION_00]
LINK_TYPE=serial
SERIAL_PORT=/dev/ttyUSB0
SERIAL_BAUD=9600
SERIAL_BITS=8
SERIAL_PARITY=none
SERIAL_STOP=1
MB_SLAVE_ID=1
SERIAL_DELAY_MS=10
#MB_TX_CODE=fnct_05_write_single_coil
#MB_TX_CODE=fnct_03_read_holding_registers
MB_TX_CODE=fnct_06_write_single_register
FIRST_ELEMENT=8192
#NELEMENTS=11
PIN_NAMES=spindle_start_stop
MB_RESPONSE_TIMEOUT_MS=400
MB_BYTE_TIMEOUT_MS=500
MAX_UPDATE_RATE=0.0
MB_MAX_RETRIES=3
DEBUG=3

[TRANSACTION_01]
LINK_TYPE=serial
SERIAL_PORT=/dev/ttyUSB0
SERIAL_BAUD=9600
SERIAL_BITS=8
SERIAL_PARITY=none
SERIAL_STOP=1
MB_SLAVE_ID=1
SERIAL_DELAY_MS=10
#MB_TX_CODE=fnct_05_write_single_coil
#MB_TX_CODE=fnct_03_read_holding_registers
MB_TX_CODE=fnct_06_write_single_register
FIRST_ELEMENT=4096
#NELEMENTS=11
PIN_NAMES=spindle_frequency_set
MB_RESPONSE_TIMEOUT_MS=400
MB_BYTE_TIMEOUT_MS=500
MAX_UPDATE_RATE=0.0
MB_MAX_RETRIES=3
DEBUG=3
